### ISSUE TITLE
Stabby page is missing some things

### ISSUE THREAD

**Issue by ravenbuilder934** [sciwhiz12/sciwhiz12.github.io#11]
At the moment, https://sciwhiz12.tk/fun/stabby.html doesn't have:

- [ ] A title when you hover over the tab
- [ ] The ability to download the stabby as a GIF (even if you right-click on it)
- [ ] A link to the page
- [ ] A header (which also means it doesn't have a way to get back to the homepage)

**Comment by sciwhiz12** [comment]
Technically I only inteded for stabby to be a temporary page, but I'll think on making it permanent.
And it's not downloadable as a GIF because it's actually a CSS animation of two SVGs (the knife and the bolb). I'll probably just add the GIF as a link.
